  @startuml
  ' ---------- SETUP ----------------
  ' strict uml style and hide footboxes
  skinparam style strictuml
  hide footbox
  ' for anchors and duration this may be required (uncomment)
  ' !pragma teoz true

  ' ---------- Declaring participants
  ' participant Participant as Foo
  
  actor User
  box "MDO-RC" #LightBlue
  boundary "UI" as UI
  control "UI Engine" as UIE
  actor "Remote Client \nBack-End" as RC
  endbox
  box "MDO-RS" #f9db8f
  actor "Remote Server" as RS
  database "User DB" as UserDB
  endbox
  ' entity      Entity      as Foo4
  ' database    Database    as Foo5
  ' collections Collections as Foo6
  ' queue       Queue       as Foo7

  ' async message
  == Application start ==
  activate User
  User ->> UI: starts app 
  deactivate User
  activate UI
  UI -> User: Show Login view
  deactivate UI
''
  == Login ==
  activate User
  User ->> UI: input username and password
  deactivate User
  activate UI
  UI -> User: visual feedback
  deactivate UI
  activate User
  User ->> UI: User presses Login
''
  deactivate User
  activate UI
  UI -> UIE: login_btn_pressed
  deactivate UI
  activate UIE
  UIE -> RC : login(username, pass)
  deactivate UIE
  activate RC
  RC -> RC : Encrypt password
  RC ->> RS : send(username, pass_crypt)
  activate RS
  RS -> UserDB : transaction(username, pass_crypt)
  activate UserDB
'' DB transaction
  alt transaction success
    UserDB -> RS: User info
    RS ->> RC: User info
    RC -> RC: check type of User
    alt Admin user
      RC -> UIE: admin user
      activate UIE
      UIE -> UI: admin_view
      deactivate UIE
      activate UI
      UI -> User: Show admin view
      activate User
      deactivate UI
      ref over RC, UIE, UI, User: Admin
      deactivate User  
    else Brand user
      RC -> UIE: brand user
      activate UIE
      UIE -> UI: brand_view
      deactivate UIE
      activate UI
      UI -> User: Show brand view
      activate User
      deactivate UI
      deactivate User
      ref over RC, UIE, UI, User: Brand
    end
  else failure
  UserDB -> RS: empty
  deactivate UserDB
  RS ->> RC : empty
  deactivate RS
  RC -> UIE : login fail
  activate UIE
  UIE -> UI : login_fail_view
  deactivate UIE
  activate UI
  UI -> User : Show login fail view
  deactivate UI
  activate User
  deactivate User
  end
''
''  == User Authentication ==
''  alt Admin
''    UIE ->> RC : Send DBs relative to admin
''    RC ->> User : Show Main Menu
''    alt Users
''      User ->> RC : Manage Useres
''      RC ->> UIE : Send changes
''      UIE ->> UIE : Update data
''    else Statistics
''      User ->> RC : Watch Statistics
''      RC ->> User : Show Statistics
''    else Ads To Activate
''      User ->> RC : Download Videos, Accept/Deny Ads
''      RC ->> UIE : Send Changes
''      UIE ->> UIE : Update data
''    else Logout
''      User ->> RC : Logout
''      RC ->> RC : Quit
''    end
'    
''  else Brand
''    UIE ->> RC : Sends DBs relative to the brand 
''    RC ->> User : Show Main Menu
''    alt Notifications
''      User ->> RC : See notifications
''      RC ->> User : Show notifications
''    else Rented
''      User ->> RC : See Rented Ads
''      RC ->> User : Show statistics of Rented Ads
''    else To Rent
''      User ->> RC : Upload Videos, choose conditions and fragrancy
''      RC ->> UIE : Send Changes
''      UIE ->> UIE : Update data
''    else Logoudat
''      User ->> RC : Logout
''      RC ->> RC : Quit
''    end
''  end

' =========================== ZE das couves ==============================='
'  LS -> UIE: show Image Filter view
'  UIE -> User: visual feedback
'  ref over User, GRE, UIE, LS: Image Filter
' -------
'    else Take Pic
'    LS -> UIE: show Pic view
'    UIE -> User: visual feedback
'    ref over User, GRE, UIE, LS: Picture mode
' -------
'    else Create GIF
'    LS -> UIE: show GIF view
'    UIE -> User: visual feedback
'    ref over User, GRE, UIE, LS: GIF mode
'    '' LS -> LS: process gesture \ncallback
'    '' LS -> UIE: provide output
'    '' UIE -> User: visual feedback
'    ' end alt
'    end 
' end par
'  end
		

  @enduml
