@startuml
'-----------------------
  note right
    Thread to handle 
    DB queries
  end note
'-----------------------
start
    repeat

        :pthread_mutex_lock(&dbQueriesAccess)
        query = dbQueries.pop()
        pthread_mutex_unlock(&dbQueriesAccess);
        repeat
            if(making_query == 1) then (Yes)
              :wait;
            else (No)
            endif
            :pthread_cond_signal(&making_query)
            send query to the DB;
            note left
                send the query and wait
                for the DB response
            end note
            :wait for response;
        repeat while(response received?) is (No) not (Yes)
        :making_query = 0
        Construct the response rxFrame
        Construct the send serverFrame;
        :pthread_mutex_lock(&TxVecAccess)
        txVec.push(response)
        pthread_mutex_unlock(&TxVecAccess)
        pthread_con_signal(&msgTx);
    repeat while(execution aborted?) is (No) not (Yes)
    stop
'-----------------------
@enduml