@startuml
'-----------------------
  note right
    Thread to update 
    local system
  end note
'-----------------------
start
    repeat
        if (received trigger from database?) then (Yes)
            
            :make query to the specific database;
            note left
                when a DB is updated
                it triggers and sends
                that trigger to the RS
                sending the station and the
                table that have been updated
            end note
            :wait for response;
            :pthread_mutex_lock(&TxVecAccess);
            note left
                Lock mutex to access
                tx local vector
            end note
            :push to LocTxVec the data to send;
            :pthread_cond_signal(&msgTx)
            pthread_mutex_unlock(&TxVecAccess);
            note left
                Unlock mutex and signal
                that has something to send to local
            end note
        else (No)
        endif
    repeat while(execution aborted?) is (No) not (Yes)
    stop
'-----------------------
@enduml